
import { ShoppingList, ListItem, Transaction, ExpenseCategory, Store, Category } from './types';

export const initialStores: Store[] = [
    { id: '1', name: 'Continente', icon: '🛒', color: '#2ECC71' },
    { id: '2', name: 'Pingo Doce', icon: '🥬', color: '#3B82F6' },
    { id: '3', name: 'Lidl', icon: '🥨', color: '#F59E0B' },
    { id: '4', name: 'Auchan', icon: '🐦', color: '#EF4444' },
];

export const initialCategories: Category[] = [
    { id: '1', name: 'Frescos' },
    { id: '2', name: 'Padaria' },
    { id: '3', name: 'Laticínios' },
    { id: '4', name: 'Congelados' },
    { id: '5', name: 'Talho' },
    { id: '6', name: 'Mercearia' },
    { id: '7', name: 'Limpeza' },
    { id: '8', name: 'Bebidas' },
    { id: '9', name: 'Outros' },
];

export const translations = {
    en: {
        'welcome_title': 'Smart Shopping & Finance',
        'welcome_desc': 'Manage your spending, maximize your savings and control your money.',
        'nav_lists': 'Lists',
        'nav_expenses': 'Finance',
        'nav_profile': 'Profile',
        'default_user': 'User',
        'biometric_login': 'Biometric Entry',
        'biometric_not_enabled': 'Biometrics not enabled in settings.',
        'biometric_failed': 'Biometric authentication failed.',
        'setup_profile': 'Setup Profile',
        'complete_profile_desc': 'Tell us a bit more about you to personalize your experience.',
        'finish_setup': 'Finish Setup',
        'enable_biometrics': 'Enable Biometrics',
        'biometrics_desc': 'Use FaceID or TouchID for quick entry.',
        'my_profile': 'My Profile',
        'member_since': 'Member since',
        'personal_info': 'PERSONAL INFO',
        'preferences': 'PREFERENCES',
        'security': 'SECURITY',
        'terminate_session': 'Sign Out',
    },
    pt: {
        'app_name': 'Compras Inteligentes & Finanças',
        'start': 'Começar',
        'next': 'Próximo',
        'skip': 'Pular',
        'get_started': 'Começar a Usar',
        'save': 'Guardar',
        'cancel': 'Cancelar',
        'delete': 'Apagar',
        'edit': 'Editar',
        'done': 'Concluir',
        'confirm_delete_list': 'Tem a certeza que quer apagar esta lista?',
        'export': 'Exportar',
        'import': 'Importar',
        'welcome_title': 'Compras & Finanças Inteligentes',
        'welcome_desc': 'Faça a gestão dos seus gastos, maximize as suas poupanças e controle o seu dinheiro.',
        'biometric_login': 'Entrada Biométrica',
        'biometric_not_enabled': 'Biometria não ativada nas definições.',
        'biometric_failed': 'Falha na autenticação biométrica.',
        'setup_profile': 'Configurar Perfil',
        'complete_profile_desc': 'Diga-nos um pouco mais sobre si para personalizar a sua experiência.',
        'finish_setup': 'Finalizar Configuração',
        'enable_biometrics': 'Ativar Biometria',
        'biometrics_desc': 'Use FaceID ou TouchID para entrar rapidamente.',
        'dashboard_title': 'Bem-vindo de volta,',
        'default_user': 'Utilizador',
        'my_profile': 'O Meu Perfil',
        'member_since': 'Membro desde',
        'personal_info': 'INFORMAÇÕES PESSOAIS',
        'preferences': 'PREFERÊNCIAS',
        'security': 'SEGURANÇA',
        'terminate_session': 'Terminar Sessão',
        'nav_lists': 'Listas',
        'nav_expenses': 'Finanças',
        'nav_profile': 'Perfil',
    }
};
