
import { ShoppingList, ListItem, Transaction, Budget, Store, Category } from './types';

// Configuração do Google Client ID
// IMPORTANTE: Este ID é um exemplo. Para o Login Google funcionar no seu ambiente de preview,
// você deve criar um projeto na Google Cloud Console, configurar o OAuth Consent Screen,
// criar credenciais de OAuth Client ID para Web Application, e adicionar a URL do seu preview
// (ex: https://ais-dev-....run.app) em "Authorized JavaScript origins".
// Depois, substitua o valor abaixo pelo seu novo Client ID.
export const GOOGLE_CLIENT_ID = "295756909371-bvb5em9csgbl2s6qvjc4r6g21hj1ob0q.apps.googleusercontent.com";

export const initialStores: Store[] = [
    { id: '1', name: 'Continente', icon: '🛒', color: '#2ECC71' },
    { id: '2', name: 'Pingo Doce', icon: '🥬', color: '#3B82F6' },
    { id: '3', name: 'Lidl', icon: '🥨', color: '#F59E0B' },
    { id: '4', name: 'Auchan', icon: '🐦', color: '#EF4444' },
];

export const initialCategories: Category[] = [
    { id: '1', name: 'Frescos', color: '#10B981' }, // Emerald
    { id: '2', name: 'Padaria', color: '#F59E0B' }, // Amber
    { id: '3', name: 'Laticínios', color: '#3B82F6' }, // Blue
    { id: '4', name: 'Congelados', color: '#06B6D4' }, // Cyan
    { id: '5', name: 'Talho', color: '#EF4444' }, // Red
    { id: '6', name: 'Mercearia', color: '#8B5CF6' }, // Violet
    { id: '7', name: 'Limpeza', color: '#14B8A6' }, // Teal
    { id: '8', name: 'Bebidas', color: '#EC4899' }, // Pink
    { id: '9', name: 'Outros', color: '#6B7280' }, // Gray
];

export const translations = {
    en: {
        'welcome_title': 'Smart Shopping',
        'share_list': 'Share List',
        'share_not_supported': 'Sharing is not supported on this device.',
        'archive': 'Archive',
        'unarchive': 'Unarchive',
        'copy_list': 'Copy List',
        'finish_shopping_archive_info': 'When finishing, the entire list will be archived with today\'s date to keep history.',
        'archive_list_after_shopping': 'Archive list for history',
        'finish_shopping': 'Finish Shopping',
        'finish_shopping_info': 'When finishing, these items will be saved in your Shopping History and removed from this list.',
        'total_spent': 'Total Spent',
        'spending_by_category': 'Spending by Category',
        'spent_this_month': 'Spent this Month',
        'purchases': 'purchases',
        'recent_purchases': 'Recent Purchases',
        'spending_by_store': 'Spending by Store',
        'spent': 'Spent',
        'view_history': 'View History',
    },
    pt: {
        'all': 'Todos',
        'app_name': 'Compras Inteligentes & Finanças',
        'start': 'Começar',
        'next': 'Seguinte',
        'skip': 'Saltar',
        'get_started': 'Começar a Usar',
        'save': 'Guardar',
        'cancel': 'Cancelar',
        'delete': 'Apagar',
        'edit': 'Editar',
        'done': 'Concluir',
        'confirm': 'Confirmar',
        'confirm_delete_list': 'Apagar Lista?',
        'confirm_delete_list_msg': 'Tem a certeza que deseja apagar a lista',
        'confirm_delete_item': 'Apagar Artigo?',
        'confirm_delete_item_msg': 'Tem a certeza que deseja apagar o artigo',
        'confirm_delete_transaction': 'Tem a certeza que deseja apagar esta transação?',
        'confirm_bulk_delete': 'Tem a certeza que quer apagar todos os itens selecionados?',
        'confirm_delete_store': 'Apagar Loja?',
        'confirm_delete_store_msg': 'Tem a certeza que deseja apagar a loja',
        'confirm_delete_category': 'Apagar Categoria?',
        'confirm_delete_category_msg': 'Tem a certeza que deseja apagar a categoria',
        'export': 'Exportar',
        'import': 'Importar',
        'welcome_title': 'Compras & Finanças Inteligentes',
        'welcome_desc': 'Faça a gestão dos seus gastos, maximize as suas poupanças e controle o seu dinheiro com inteligência artificial.',
        'biometric_login': 'Entrada Biométrica',
        'biometric_not_enabled': 'Biometria não ativada nas definições.',
        'biometric_failed': 'Falha na autenticação biométrica.',
        'setup_profile': 'Configurar Perfil',
        'complete_profile_desc': 'Importámos os seus dados. Confirme as informações e configure a segurança para continuar.',
        'finish_setup': 'Finalizar Configuração',
        'enable_biometrics': 'Ativar Biometria',
        'biometrics_desc': 'Use FaceID ou TouchID para entrar rapidamente na App.',
        'biometrics_enabled_msg': 'Biometria ativada. Use a sua impressão digital ou FaceID no próximo login.',
        'biometrics_disabled_msg': 'Biometria desativada.',
        'dashboard_title': 'Bem-vindo de volta,',
        'default_user': 'Utilizador',
        'my_profile': 'O Meu Perfil',
        'member_since': 'Membro desde',
        'personal_info': 'INFORMAÇÕES PESSOAIS',
        'full_name': 'Nome Completo',
        'email': 'Email',
        'preferences': 'PREFERÊNCIAS',
        'settings': 'DEFINIÇÕES',
        'security': 'SEGURANÇA',
        'terminate_session': 'Terminar Sessão',
        'nav_lists': 'Listas',
        'nav_dashboard': 'Dashboard',
        'nav_budget': 'Orçamento',
        'nav_settings': 'Definições',
        'nav_profile': 'Perfil',
        'total_balance': 'Saldo Total',
        'monthly_spending': 'Gastos do Mês',
        'monthly_income': 'Rendimentos do Mês',
        'monthly': 'Mensal',
        'health_score': 'Pontuação Financeira',
        'recent_transactions': 'Transações Recentes',
        'view_all_transactions': 'Ver Todas',
        'add_transaction': 'Nova Transação',
        'edit_transaction': 'Editar Transação',
        'transaction_description': 'Descrição',
        'transaction_amount': 'Valor',
        'transaction_type': 'Tipo',
        'income': 'Rendimento',
        'expense': 'Despesa',
        'recurring': 'Recorrente',
        'smart_insights_title': 'Insights Inteligentes',
        'no_insights': 'Ainda não temos insights para si. Continue a registar as suas despesas!',
        'budget_title': 'Orçamentos',
        'add_budget': 'Novo Orçamento',
        'no_budget_categories': 'Para começar, adicione categorias de orçamento nas Definições.',
        'budget_limit': 'Limite',
        'budget_spent': 'Gasto',
        'budget_remaining': 'Restante',
        'optimization_tips': 'Dicas de Otimização',
        'predictive_analysis': 'Análise Preditiva',
        'financial_health': 'Saúde Financeira',
        'shopping_lists_title': 'Listas de Compras',
        'search_lists_placeholder': 'Pesquisar listas...',
        'all_stores': 'Todas',
        'active': 'Ativas',
        'archived': 'Arquivadas',
        'shared': 'Partilhadas',
        'edit_list': 'Editar Lista',
        'list_name': 'Nome da Lista',
        'list_icon': 'Ícone',
        'store': 'Loja',
        'select_store': 'Selecione uma loja',
        'select_category': 'Selecione uma categoria',
        'total_estimated': 'TOTAL ESTIMADO',
        'articles': 'ARTIGOS',
        'progress': 'Progresso',
        'pending': 'Pendentes',
        'completed': 'Comprados',
        'name': 'Nome',
        'price': 'Preço',
        'category': 'Categoria',
        'selection_mode': 'Seleção',
        'items_selected': 'selecionados',
        'deselect_all': 'Desmarcar',
        'bulk_mark_done': 'Comprado',
        'bulk_category': 'Categoria',
        'bulk_move': 'Mover',
        'bulk_delete': 'Apagar',
        'quick_add_placeholder': 'Adição rápida (ex: Leite)...',
        'move_to': 'Mover para...',
        'select_destination_list': 'Selecione a lista de destino',
        'no_other_lists': 'Não existem outras listas ativas.',
        'add_item_title': 'Adicionar Artigo',
        'edit_item_title': 'Editar Artigo',
        'item_image': 'Imagem do Artigo',
        'take_photo': 'Tirar Foto',
        'generate_image': 'Gerar com IA',
        'generating_image': 'A gerar...',
        'item_name': 'Nome do Artigo',
        'ai_suggestions': 'Sugerir Detalhes',
        'quantity': 'Quantidade',
        'unit': 'Unidade',
        'price_optional': 'Preço (Opcional)',
        'crop_image': 'Ajustar Imagem',
        'drag_to_position': 'Arraste para posicionar',
        'zoom': 'Zoom',
        'apply': 'Aplicar',
        'manage_stores': 'Gerir Lojas',
        'store_name': 'Nome da Loja',
        'manage_categories': 'Gerir Categorias (Listas)',
        'manage_budget_categories': 'Gerir Categorias (Orçamento)',
        'user_manual': 'Manual de Utilização',
        'category_name': 'Nome da Categoria',
        'dark_mode': 'Modo Escuro',
        'total_spent_this_month': 'Total Gasto Este Mês',
        'used': 'Usado',
        'remaining': 'Restante',
        'expenses_by_category': 'Despesas por Categoria',
        'view_all': 'Ver Tudo',
        'no_expenses': 'Sem despesas registadas.',
        'recent_activity': 'Atividade Recente',
        'empty_dashboard': 'Sem atividade recente.',
        'export_as_pdf': 'Exportar como PDF',
        'export_as_excel': 'Exportar como Excel',
        'export_as_csv': 'Exportar como CSV',
        'select_file': 'Selecionar Ficheiro',
        'download_template': 'Descarregar Modelo',
        'promotions_for': 'Promoções para',
        'no_promotions_found': 'Não foram encontradas promoções.',
        'price_alert': 'Alerta de Preço',
        'no_price_change': 'O preço mantém-se estável.',
        'price_up': 'O preço subiu desde a última verificação.',
        'price_down': 'O preço desceu! Boa altura para comprar.',
        'previous_price': 'Preço Anterior',
        'new_price': 'Preço Novo',
        'view_source': 'Ver Fonte',
        'share_list': 'Partilhar Lista',
        'share_not_supported': 'A partilha não é suportada neste dispositivo.',
        'archive': 'Arquivar',
        'unarchive': 'Desarquivar',
        'copy_list': 'Copiar Lista',
        'finish_shopping_archive_info': 'Ao finalizar, a lista inteira será arquivada com a data de hoje para manter o histórico.',
        'archive_list_after_shopping': 'Arquivar lista para histórico',
        'finish_shopping': 'Finalizar Compra',
        'finish_shopping_info': 'Ao finalizar, estes artigos serão guardados no seu Histórico de Compras e removidos desta lista.',
        'total_spent': 'Total Gasto',
        'spending_by_category': 'Gastos por Categoria',
        'spent_this_month': 'Gasto este Mês',
        'purchases': 'compras registadas',
        'recent_purchases': 'Compras Recentes',
        'spending_by_store': 'Gastos por Loja',
        'spent': 'Gasto',
        'view_history': 'Ver Histórico',
        'export_csv': 'CSV',
        'onboarding_welcome_title': 'Bem-vindo ao SmartShop',
        'onboarding_welcome_desc': 'A sua nova forma de organizar compras e gerir despesas de forma inteligente.',
        'onboarding_lists_title': 'Listas Inteligentes',
        'onboarding_lists_desc': 'Crie listas organizadas por loja e categoria automaticamente.',
        'onboarding_sync_title': 'Sincronização',
        'onboarding_sync_desc': 'Aceda aos seus dados em qualquer dispositivo e partilhe com a família.',
        'signin_with': 'Entrar com o Google',
        'continue_with': 'Continuar com o Google'
    }
};
